import Head from 'next/head'
import { GetStaticProps } from 'next'
import { graphqlClient } from '@/api/clients/graphql'
import { GET_ALL_BUDGET_BOXES } from '@/graphql/queries/budgetBox'
import { BudgetBoxCard } from '@/components/cards/BudgetBoxCard'
import { BudgetBox } from '@/types/BudgetBox'

interface IHome {
  budgetBoxes: Array<BudgetBox>
}

export const getStaticProps: GetStaticProps = async () => {
  try {
    const { data } = await graphqlClient.query({
      query: GET_ALL_BUDGET_BOXES,
      fetchPolicy: 'network-only'
    })
    const { budgetBoxes } = data

    return {
      props: {
        budgetBoxes
      }
    }
  } catch (e) {
    return {
      props: {
        budgetBoxes: []
      },
      revalidate: 60
    }
  }
}

export default function Home({ budgetBoxes }: IHome) {
  return (
    <div>
      <Head>
        <title>Budget Boxes</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className="px-4 md:px-14">
        <div className="grid justify-items-center gap-y-8 px-4 pt-16 sm:px-0 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5 ">
          {budgetBoxes.map((budgetBox: BudgetBox) => (
            <BudgetBoxCard key={budgetBox.id} budgetBox={budgetBox} />
          ))}
        </div>
      </main>
    </div>
  )
}
